version: 2.1

executors:
  default:
    docker:
      - image: circleci/python:3.8

jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install Azure CLI
          command: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - run:
          name: Install kubectl
          command: |
            az aks install-cli
      - run:
          name: Login to Azure
          command: |
            az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
      - run:
          name: Build Docker Image
          command: |
            docker build -t myapp:${CIRCLE_SHA1} .
      - run:
          name: Push Docker Image to ACR
          command: |
            docker login $AZURE_REGISTRY -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET
            docker tag myapp:${CIRCLE_SHA1} $AZURE_REGISTRY/myapp:${CIRCLE_SHA1}
            docker push $AZURE_REGISTRY/myapp:${CIRCLE_SHA1}
      - run:
          name: AKS Deployment
          command: |
            az aks get-credentials --resource-group myResourceGroup --name myAKSCluster
            kubectl apply -f deployment.yaml

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy
