apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleci-test-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: circleci-test
  template:
    metadata:
      labels:
        app: circleci-test
    spec:
      containers:
      - name: circleci-test
        image: khawla2.azurecr.io/circleci-test:latest
        ports:
        - containerPort: 80
