apiVersion: apps/v1
kind: Deployment
metadata:
  name: circlecitest-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: circlecitest
  template:
    metadata:
      labels:
        app: circleci-test
    spec:
      containers:
      - name: circlecitest
        image: khawla2.azurecr.io/circlecitest:latest
        ports:
        - containerPort: 80
